services:
  - type: web
    name: platenet-api
    env: node
    region: frankfurt
    plan: free

    buildCommand: |
      export NODE_OPTIONS="--max-old-space-size=1024"
      npm install
      npm run build
      npm prune --production

    startCommand: npm run start:render
    healthCheckPath: /api
    autoDeploy: true

    disk:
      name: uploads
      mountPath: /opt/render/uploads
      sizeGB: 1

    envVars:
      - key: NODE_ENV
        value: production

      - key: NODE_OPTIONS
        value: --max-old-space-size=256

      - key: UPLOAD_PATH
        value: /opt/render/uploads

      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
