# docker-compose.yml
version: '3.8'
services:
  mongodb:
    image: mongo:5
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-init:
    image: mongo:5
    depends_on:
      - mongodb
    command: >
      bash -c "
        sleep 10 &&
        mongosh --host mongodb:27017 --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongodb:27017\"}]})' &&
        mongosh --host mongodb:27017 --eval 'rs.status()'
      "

volumes:
  mongodb_data: